# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
dist: trusty

addons:
  apt:
    packages:
      - doxygen
      - graphviz

install:
  - GTEST_VERSION=1.8.1
    ; GTEST_PREFIX=~/.local/
    ; wget https://github.com/google/googletest/archive/release-${GTEST_VERSION}.tar.gz
    && tar xf release-${GTEST_VERSION}.tar.gz
    && ( cd googletest-release-${GTEST_VERSION}/
      && cmake -DCVF_VERSION=${GTEST_VERSION} -DCMAKE_INSTALL_PREFIX:PATH=${GTEST_PREFIX} .
      && make
      && make install )
    && export PKG_CONFIG_PATH="$(find "${GTEST_PREFIX}" -type d -name pkgconfig)"
  - sed 's,-I,-isystem ,g' -i "${PKG_CONFIG_PATH}"/gtest.pc  # suppress compile warnings
  
script:
  - set -e
  - mkdir -p build
  - cd build
  - cmake .. -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=`pwd`/install
  - cmake --build . --target install
  - cd ..
  - rm -fr build 

  - ./autogen.sh
  - mkdir -p build
  - cd build
  - ../configure 
  - make all
  - make check
  - cat test/uriparser_test.log
  - make distcheck  # without AddressSanitizer
