# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
dist: trusty

addons:
  apt:
    packages:
      - doxygen
      - graphviz

cache:
  directories:
    - $HOME/download

init:
  - export CPU_NUM=`cat /proc/cpuinfo |grep 'cpu cores' |wc -l`
  
install:
  - | 
    GTEST_VERSION=1.8.1 
    GTEST_PREFIX=~/.local/ 
    if [ ! -f $HOME/download/release-${GTEST_VERSION}.tar.gz ]; then 
        mkdir -p $HOME/download
        wget -O $HOME/download/release-${GTEST_VERSION}.tar.gz https://github.com/google/googletest/archive/release-${GTEST_VERSION}.tar.gz 
    fi
    tar xf $HOME/download/release-${GTEST_VERSION}.tar.gz -C .
    cd googletest-release-${GTEST_VERSION}/ 
    cmake -DCVF_VERSION=${GTEST_VERSION} -DCMAKE_INSTALL_PREFIX:PATH=${GTEST_PREFIX} . 
    cmake --build . --target install 
    export PKG_CONFIG_PATH="$(find "${GTEST_PREFIX}" -type d -name pkgconfig)" 
    
  - sed 's,-I,-isystem ,g' -i "${PKG_CONFIG_PATH}"/gtest.pc  # suppress compile warnings
  
script:
  - set -e
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p build
  - cd build
  - cmake .. -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX=`pwd`/install
  - cmake --build . --target install
  - cd ..
  - rm -fr build 

  - ./autogen.sh
  - mkdir -p build
  - cd build
  - ../configure 
  - make all -j
  - make check -j${CPU_NUM}
  - cat test/uriparser_test.log
  - make distcheck -j${CPU_NUM} # without AddressSanitizer
